### ISSUE TITLE
Use views in concretization

### ISSUE THREAD

**Issue by phipsgabler** [TuringLang/AbstractPPL.jl#49]
To concretize, we need the runtime shapes, and to get them, we actually apply the lenses: https://github.com/TuringLang/AbstractPPL.jl/blob/9b64dd89dcde2dc0d8845cd01b4cc305ea83086e/src/varname.jl#L428

It would be good if this were only views. Related: https://github.com/TuringLang/DynamicPPL.jl/issues/341

**Comment by torfjelde** [comment]
It would be nice if something like `Base.maybeview` was implemented for lenses

**Comment by phipsgabler** [comment]
Yea, I thought about this yesterday after writing. Maybe we can implement some utils locally and then ask the Setfield people whether they want them (although they explicitely exclude new stuff for Setfield, IIRC...)

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/AbstractPPL.jl/pull/43?

**Comment by phipsgabler** [comment]
No, it's not fixed, the implementation of `get` uses normal indexing (see linked issue).
